%YAML 1.2
---
command:
  name: cycle
  description: manage cycles
  usage: cycle [options] <command>
  commands:
    -
      name: init
      description: Create a new Cycle
      usage: init [options]
      options:
        -
          name: hours
          help: The maximum scoped billable hours for this cycle.
    -
      name: launch
      description: Tally votes and create project teams.
      usage: launch [options]
    -
      name: reflect
      description: Initiate reflection process.
      usage: reflect [options]
    -
      name: status
      description: Display status information for the cycle.
      usage: status [options]
      _inactive: true
  examples:
    -
      example: cycle init --help
      description: Get help on initializing a cycle.
    -
      example: cycle init --hours=32
      description: Initialize a cycle with a maximum of 32 scoped billable hours.
    -
      example: cycle reflect
      description: Start the reflection (retrospective and review) process for the current cycle.
