%YAML 1.2
---
command:
  name: cycle
  description: manage cycles
  usage: cycle [options] <command>
  commands:
    -
      name: launch
      description: Tally votes and create project teams.
      usage: launch [options]
    -
      name: reflect
      description: Initiate reflection process.
      usage: reflect [options]
    -
      name: status
      description: Display status information for the cycle.
      usage: status [options]
      _inactive: true
