%YAML 1.2
---
command:
  name: log
  description: Log reflections.
  usage: log [<command> | -r<num> <...reflection>]
  commands:
    -
      name: retro
      description: Show list of retrospective questions for reflection.
      usage: retro [options]
  options:
    -
      name: reflection
      abbr: r
      help: Specify the number of the reflection being logged. Use `log retro` to see the list of questions.
