%YAML 1.2
---
command:
  name: log
  description: Log reflections.
  usage: log [-r | -r<num> <...reflection>]
  options:
    -
      name: reflection
      abbr: r
      help: Without a number argument, show list of retrospective questions for reflection. With a number, log a reflection for the question corresponding to the number.
