%YAML 1.2
---
command:
  name: log
  description: log reflections
  usage: log [<command> | -r<num> <...reflection>]
  commands:
    -
      name: retro
      description: begin retrospective process
      usage: retro [options]
  options:
    -
      name: reflection
      abbr: r
      help: the number of the reflection being logged
