%YAML 1.2
---
command:
  name: project
  description: manage projects
  usage: project [options] <command>
  commands:
    -
      name: set-artifact
      description: Set the artifact for a project.
      usage: set-artifact [options] <project id> <url>
      examples:
        -
          example: 'project set-artifact bad-lemurs-12 https://github.com/reactjs/redux'
          description: 'Set the artifact for the bad-lemurs-12 project.'
    -
      name: list
      description: List all active projects.
      usage: list [options]
      options:
        -
          name: in-review
          abbr: r
          boolean: true
          help: List projects that are in review.
  examples:
    -
      example: 'project set-artifact bad-lemurs-12 https://github.com/reactjs/redux'
      description: 'Set the artifact for the bad-lemurs-12 project.'
    -
      example: project list -r
      description: List projects that are in review.
