%YAML 1.2
---
command:
  name: review
  description: provide feedback on a project
  usage: review <project> [options]
  options:
    -
      name: completeness
      abbr: c
      help: A score between 1-100 indicating how complete you believe the project is.
    -
      name: quality
      abbr: q
      help: A score between 1-100 indicating your perception of the quality of this project.
  examples:
    -
      example: 'review #fantastic-falcon'
      description: Show review status and atrifact URL for the fantastic-falcon project.
    -
      example: 'review #fantastic-falcon --completeness 89 --quality 93'
      description: Rate the completeness and quality of the fantastic-falcon project.
