%YAML 1.2
---
command:
  name: vote
  description: vote-rank goals for the next cycle
  usage: 'vote [options] [<first choice issue # or url> <second choice issue # or url>]'
  examples:
    -
      example: vote 23 44
      description: Vote for goals with IDs 23 and 44. (with 23 being your first choice)
    -
      example: vote --help
      description: Get help with voting.
